# Generated by Django 4.2.4 on 2024-02-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='captValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=255)),
                ('parameter_name', models.CharField(max_length=255)),
                ('sr_no', models.IntegerField()),
                ('single_radio', models.BooleanField(default=False)),
                ('analog_zero', models.FloatField(blank=True, null=True)),
                ('reference_value', models.FloatField(blank=True, null=True)),
                ('double_radio', models.BooleanField(default=False)),
                ('high_mv', models.FloatField(blank=True, null=True)),
                ('low_mv', models.FloatField(blank=True, null=True)),
                ('probe_no', models.FloatField()),
                ('measurement_mode', models.CharField(max_length=50)),
                ('nominal', models.FloatField()),
                ('usl', models.FloatField()),
                ('lsl', models.FloatField()),
                ('mastering', models.FloatField()),
                ('step_no', models.FloatField()),
                ('hide_checkbox', models.BooleanField(default=False)),
            ],
        ),
    ]
