# Generated by Django 4.2.4 on 2024-04-18 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mastering',
            new_name='mastering_data',
        ),
    ]
