# Generated by Django 4.2.4 on 2024-05-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_mastering_mastering_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100)),
                ('readings', models.FloatField()),
                ('nominal', models.FloatField()),
                ('lsl', models.FloatField()),
                ('usl', models.FloatField()),
                ('status_cell', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('operator', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=100)),
                ('machine', models.CharField(max_length=100)),
                ('part_model', models.CharField(max_length=100)),
                ('part_status', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('comp_sr_no', models.CharField(max_length=100)),
            ],
        ),
    ]
