# Generated by Django 4.2.4 on 2024-05-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_measurementdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementdata',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
