# Generated by Django 5.1 on 2024-08-30 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customerdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerDetails',
        ),
    ]
