# Generated by Django 5.1 on 2024-08-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_customerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('primary_contact_person', models.CharField(max_length=100)),
                ('secondary_contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_email', models.CharField(max_length=100)),
                ('secondary_email', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_phone_no', models.CharField(max_length=20)),
                ('secondary_phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('dept', models.CharField(max_length=100)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
            ],
        ),
    ]
