# Generated by Django 4.2.4 on 2024-06-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_measurementdata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterIntervalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timewise', models.BooleanField(default=False)),
                ('componentwise', models.BooleanField(default=False)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('minute', models.IntegerField(blank=True, null=True)),
                ('component_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
