# Generated by Django 4.2.4 on 2024-04-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_masterdata_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='comport_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_port', models.CharField(max_length=50)),
                ('baud_rate', models.IntegerField()),
                ('bytesize', models.IntegerField()),
                ('timeout', models.CharField(max_length=50)),
                ('stopbits', models.IntegerField()),
                ('parity', models.CharField(max_length=50)),
            ],
        ),
    ]
