# Generated by Django 5.1 on 2024-08-31 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customerdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='find',
        ),
    ]
