# Generated by Django 4.2.4 on 2024-06-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_masterintervalsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=50)),
                ('shift_time', models.TimeField()),
            ],
        ),
    ]
