# Generated by Django 4.2.4 on 2024-04-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_comport_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comport_settings',
            name='timeout',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
