# Generated by Django 4.2.4 on 2024-01-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_parametervalue_analog_zero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableonedata',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
