# Generated by Django 4.2.4 on 2024-06-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_shiftsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftsettings',
            name='shift_time',
            field=models.CharField(max_length=50),
        ),
    ]
