# Generated by Django 5.1 on 2024-08-31 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_probe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='probe',
            new_name='probe_calibrations',
        ),
    ]
