# Generated by Django 5.1 on 2024-09-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_probe_probe_calibrations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableOneData',
        ),
    ]
