# Generated by Django 5.1 on 2024-09-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_tableonedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableOneData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('part_model', models.CharField(max_length=100)),
                ('part_no', models.CharField(max_length=100)),
                ('char_lmt', models.CharField(max_length=100)),
                ('hide', models.BooleanField(default=False)),
            ],
        ),
    ]
