# Generated by Django 5.1 on 2024-09-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_tableonedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter_settings',
            name='attribute',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parameter_settings',
            name='probe_no',
            field=models.CharField(max_length=255),
        ),
    ]
