# Generated by Django 5.1 on 2024-10-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_parameter_settings_attribute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Histogram_Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_model', models.CharField(max_length=100)),
                ('parameter_name', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('formatted_from_date', models.CharField(max_length=100)),
                ('formatted_to_date', models.CharField(max_length=100)),
                ('machine', models.CharField(max_length=100)),
                ('vendor_code', models.CharField(max_length=100)),
                ('sample_size', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=100)),
                ('current_date_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pie_Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_model', models.CharField(max_length=100)),
                ('parameter_name', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('formatted_from_date', models.CharField(max_length=100)),
                ('formatted_to_date', models.CharField(max_length=100)),
                ('machine', models.CharField(max_length=100)),
                ('vendor_code', models.CharField(max_length=100)),
                ('sample_size', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=100)),
                ('current_date_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='X_Bar_Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_model', models.CharField(max_length=100)),
                ('parameter_name', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('formatted_from_date', models.CharField(max_length=100)),
                ('formatted_to_date', models.CharField(max_length=100)),
                ('machine', models.CharField(max_length=100)),
                ('vendor_code', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=100)),
                ('current_date_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='X_Bar_R_Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_model', models.CharField(max_length=100)),
                ('parameter_name', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('formatted_from_date', models.CharField(max_length=100)),
                ('formatted_to_date', models.CharField(max_length=100)),
                ('machine', models.CharField(max_length=100)),
                ('vendor_code', models.CharField(max_length=100)),
                ('sample_size', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=100)),
                ('current_date_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='X_Bar_S_Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_model', models.CharField(max_length=100)),
                ('parameter_name', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('formatted_from_date', models.CharField(max_length=100)),
                ('formatted_to_date', models.CharField(max_length=100)),
                ('machine', models.CharField(max_length=100)),
                ('vendor_code', models.CharField(max_length=100)),
                ('sample_size', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=100)),
                ('current_date_time', models.CharField(max_length=100)),
            ],
        ),
    ]
