# Generated by Django 5.1 on 2024-10-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_histogram_chart_pie_chart_x_bar_chart_x_bar_r_chart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementdata',
            name='attribte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='measurementdata',
            name='attribute_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
