# Generated by Django 4.2.4 on 2024-06-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_consolidate_with_srno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementdata',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
