# Generated by Django 5.1 on 2024-10-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_measurementdata_attribte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementdata',
            name='ltl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurementdata',
            name='utl',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
