# Generated by Django 4.2.4 on 2024-06-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_consolidate_without_srno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consolidate_without_srno',
            name='job_no',
        ),
    ]
