# Generated by Django 5.1 on 2024-10-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_measurementdata_ltl_measurementdata_utl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementdata',
            name='lsl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurementdata',
            name='nominal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurementdata',
            name='readings',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurementdata',
            name='usl',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
