# Generated by Django 5.1 on 2024-10-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_measurementdata_lsl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementdata',
            name='attribte',
        ),
        migrations.RemoveField(
            model_name='measurementdata',
            name='attribute_status',
        ),
    ]
