# Generated by Django 5.1 on 2024-10-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_measurementdata_attribte_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerDetails',
        ),
    ]
