# Generated by Django 4.2.4 on 2024-06-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_parameterwise_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobwise_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_model', models.CharField(max_length=100)),
                ('formatted_from_date', models.CharField(max_length=100)),
                ('formatted_to_date', models.CharField(max_length=100)),
                ('job_no', models.CharField(max_length=100)),
                ('current_date_time', models.CharField(max_length=100)),
            ],
        ),
    ]
