# Generated by Django 4.2.4 on 2024-06-26 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_jobwise_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterData',
        ),
    ]
