# Generated by Django 4.2.4 on 2024-06-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_delete_masterdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_model', models.CharField(max_length=100)),
                ('accept', models.CharField(blank=True, max_length=100)),
                ('reject', models.CharField(blank=True, max_length=100)),
                ('rework', models.CharField(blank=True, max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
