# Generated by Django 5.1 on 2024-10-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_customerdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pie_chart',
            name='sample_size',
        ),
    ]
