# Generated by Django 4.2.4 on 2024-06-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_resetcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resetcount',
            name='accept',
        ),
        migrations.RemoveField(
            model_name='resetcount',
            name='reject',
        ),
        migrations.RemoveField(
            model_name='resetcount',
            name='rework',
        ),
    ]
