# Generated by Django 4.2.4 on 2024-07-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_resetcount_accept_remove_resetcount_reject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobwise_report',
            name='formatted_from_date',
        ),
        migrations.RemoveField(
            model_name='jobwise_report',
            name='formatted_to_date',
        ),
    ]
