# Generated by Django 4.2.4 on 2024-07-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_jobwise_report_formatted_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastering_data',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
