# Generated by Django 4.2.4 on 2024-07-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_mastering_data_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probe_no', models.CharField(max_length=100)),
                ('a', models.FloatField()),
                ('b', models.FloatField()),
                ('e', models.FloatField()),
                ('d', models.FloatField()),
                ('o1', models.FloatField()),
                ('parameter_name', models.CharField(max_length=100)),
                ('selected_value', models.CharField(max_length=100)),
                ('selected_mastering', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('machine', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
