# Generated by Django 4.2.4 on 2024-07-08 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_master_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mastering_data',
        ),
    ]
